Add --merge flag to makemigrations in deploy.yml
Added the missing --merge flag on the django makemigrations command in the deploy.yml Ansible script.  

Ran into an issue today with remote deployment and the makemigrations --merge flag resolved this error: 
CommandError: Conflicting migrations detected; multiple leaf nodes in the migration graph.